<?php
/**
 * @file
 * Contains commerce_stock_s.module..
 */

/**
 * Implements hook_cron().
 *
 * Add products to the Location Level Q. a worker process will then update the
 * LL table.
 */
function commerce_stock_s_cron() {
  // Get the config object.
  $stock_config = \Drupal::configFactory()->getEditable('commerce_stock_s.cron');
  // Default to an hourly interval.
  $interval = $stock_config->get('interval');
  $interval = !empty($interval) ? $interval : 3600;
  // We usually don't want to act every time cron runs (which could be every
  // minute) so keep a time for the next run in the site state.
  $next_execution = \Drupal::state()->get('commerce_stock_s.next_execution');
  $next_execution = !empty($next_execution) ? $next_execution : 0;
  if (REQUEST_TIME >= $next_execution) {
    // Add products to the Q.
    commerce_stock_s_update_llq();
    // Set the next execution time.
    \Drupal::state()->set('commerce_stock_s.next_execution', REQUEST_TIME + $interval);
  }
}

/**
 * Update the Location Level Q (LLQ).
 *
 * The location level Q holds a list of product IDs to be processed by the
 * cron_stock_update_location_level queue worker.
 */
function commerce_stock_s_update_llq() {
  // Add products to the Q.
  $queue = \Drupal::queue('cron_stock_update_location_level');

  // Get the last processed product id.
  $llq_pvid = \Drupal::state()->get('commerce_stock_s.llq_pvid');
  $llq_pvid = !empty($llq_pvid) ? $llq_pvid : 0;

  // Check if Q empty and not initialized to 0.
  if (($queue->numberOfItems() == 0) && ($llq_pvid != 0)) {
    // Set the Q reset state.
    \Drupal::state()->set('commerce_stock_s.llq_reset', TRUE);
    $llq_reset = TRUE;
  }
  else {
    // Get the Q reset state.
    $llq_reset = \Drupal::state()->get('commerce_stock_s.llq_reset');
    $llq_reset = !empty($llq_reset) ? $llq_reset : FALSE;
  }
  // Get the batch size.
  $llq_batchsize = \Drupal::state()->get('commerce_stock_s.llq_batchsize');
  $llq_batchsize = !empty($llq_batchsize) ? $llq_batchsize : 50;

  $result = \Drupal::entityQuery('commerce_product_variation')
    ->condition('variation_id', $llq_pvid, '>')
    ->condition('status', 1, '=')
    ->sort('variation_id', 'ASC')
    ->range(0, $llq_batchsize)
    ->execute();
  foreach ($result as $pid) {
    $queue->createItem($pid);
  }
  // Check if we can restrt processing products from the top.
  if ($llq_reset && (count($result) < $llq_batchsize)) {
    // Set reset to FALSE.
    \Drupal::state()->set('commerce_stock_s.llq_reset', FALSE);
    // Set last product id to 0.
    \Drupal::state()->set('commerce_stock_s.llq_pvid', 0);
  }
  else {
    // Set the last product id for the Q bookmark.
    if (!empty($result)) {
      \Drupal::state()->set('commerce_stock_s.llq_pvid', $pid);
    }
  }
}
